name: WebRtcNativeMacOsStaticLib

on: workflow_dispatch

##env:
  ##DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  ##GYP_GENERATORS: msvs-ninja,ninja
  ##GYP_MSVS_OVERRIDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  ##vs2022_install: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  ##GYP_MSVS_VERSION: 2022
  ##PYTHON_BIN_ABSDIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
  ##PATH: $GITHUB_WORKSPACE/depot_tools:$PATH
  
jobs:
  build:
    runs-on: macos-latest
     
    steps:
    - uses: actions/checkout@v3    
    
    - name: Create 'depot_tools'
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: Export 'depot_tools' path
      run: echo "${{github.workspace}}/depot_tools/" >> $GITHUB_PATH
    - name: Execute 'gclient'
      run: gclient
    
    - name: Configure Git
      run: |
        git config --global user.name "melihercan"
        git config --global user.email "melihercan@gmail.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global branch.autosetuprebase always
        
    - name: Get the code and build
      run: |
        mkdir webrtc-checkout
        cd webrtc-checkout
        fetch --nohooks webrtc
        gclient sync
        cd src
        git checkout branch-heads/5481
        gclient sync
        gn gen out/Default --args='is_debug=false'
        autoninja -C out/Default
        
    - name: Copy WebRTC library
      run: |
        cp webrtc-checkout/src/out/Default/obj/libwebrtc.a .
        
    - uses: actions/upload-artifact@v3
      with: 
        name: macOS WebRTC static library (libwebrtc.a)
        path: ./libwebrtc.a
