name: WebRtcNativeIosBindings

on: workflow_dispatch
 
jobs:
  build:
    runs-on: macos-latest
     
    steps:
    - uses: actions/checkout@v3    
    
    - name: Create 'depot_tools'
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: Export 'depot_tools' path
      run: echo "${{github.workspace}}/depot_tools/" >> $GITHUB_PATH
    - name: Execute 'gclient'
      run: gclient
    
    - name: Configure Git
      run: |
        git config --global user.name "melihercan"
        git config --global user.email "melihercan@gmail.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global branch.autosetuprebase always
        
    - name: Get the code and build
      run: |
        pip install --upgrade setuptools
        mkdir webrtc-checkout
        cd webrtc-checkout
        fetch --nohooks webrtc_ios
        gclient sync
        cd src
        git checkout branch-heads/6045
        gclient sync
        #./tools_webrtc/ios/build_ios_libs.py --arch arm64 x64
        ./tools_webrtc/ios/build_ios_libs.py
        ls -l out_ios_libs
    - name: Zip the libraries
      run: |
        zip -vr out_ios_libs.zip out_ios_libs/ -x "*.DS_Store"
    - uses: actions/upload-artifact@v3
      with: 
        name: iOS WebRTC libraries 
        path: ./out_ios_libs.zip
        
